apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gateway-claim0
  namespace: standard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway--env
  namespace: standard
data:
  ORDERS_SERVICE_URL: http://orders:8000
  USERS_SERVICE_URL: http://users:8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: standard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - args:
            - sh
            - -c
            - uvicorn main:app --reload --host 0.0.0.0
          env:
            - name: ORDERS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: ORDERS_SERVICE_URL
                  name: gateway--env
            - name: USERS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: USERS_SERVICE_URL
                  name: gateway--env
          image: baranbartu/k-api-gateway:latest
          name: gateway
          ports:
          - containerPort: 8000
          volumeMounts:
            - mountPath: ./gateway:/app
              name: gateway-claim0
      restartPolicy: Always
      volumes:
        - name: gateway-claim0
          persistentVolumeClaim:
            claimName: gateway-claim0

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: standard
spec:
  selector:
    app: gateway
  type: NodePort
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8000
