apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-claim0
  namespace: standard
spec:
   accessModes:
     - ReadWriteOnce
   storageClassName: local
   resources:
     requests:
        storage: 100Mi		
---
apiVersion: v1
kind: ConfigMap
metadata:
   name: orders--env
   namespace: standard
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: orders
   namespace: standard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - args:
            - sh
            - -c
            - uvicorn main:app --reload --host 0.0.0.0
          image: baranbartu/k-orders:latest
          name: orders
          volumeMounts:
             - mountPath: /app
               name: orders-claim0
      restartPolicy: Always
      volumes:
        - name: orders-claim0
          persistentVolumeClaim:
            claimName: orders-claim0
