apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-claim0
  namespace: standard
spec:
   accessModes:
     - ReadWriteOnce
   storageClassName: local
   resources:
     requests:
       storage: 100Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
   name: users--env
   namespace: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: standard
spec:
 replicas: 1
 selector:
   matchLabels:
      app: users
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - args:
            - sh
            - -c
            - uvicorn main:app --reload --host 0.0.0.0
          image: baranbartu/k-orders:latest
          name: users
          volumeMounts:
             - mountPath: ./users: /app
               name: users-claim0
      restartPolicy: Always
      volumes:
        - name: users-claim0
          persistentVolumeClaim:
              claimName: users-claim0
