apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "examgitlab.fullname" . }}-configmaporders 
  namespace: {{ .Values.orders.namespace }}
  labels:
    {{- include "examgitlab.labels" . | nindent 4 }}
