apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "examgitlab.fullname" . }}-configmapusers
  namespace: {{ .Values.users.namespace }}
  labels:
    {{- include "examgitlab.labels" . | nindent 4 }}
