apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "examgitlab.fullname" . }}-configmapgateway 
  namespace: {{ .Values.gateway.namespace }}
  labels:
    {{- include "examgitlab.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.configmapgateway }}
  {{ $key }}: {{ $val }}
  {{- end }}
