

{{- if and .Values.persistenceorders.enabled (not .Values.persistenceorders.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "examgitlab.fullname" . }}
  namespace: {{ .Values.persistenceorders.namespace }}
{{- with .Values.persistenceorders.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ template "examgitlab.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.persistenceorders.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistenceorders.size | quote }}
{{- if .Values.persistenceorders.storageClass }}
{{- if (eq "-" .Values.persistenceorders.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistenceorders.storageClass }}"
{{- end }}
{{- end }}
{{- end }}

